name = "kusudama"
defaultTargets = ["Kusudama"]

[[require]]
name = "plausible"
git = "https://github.com/leanprover-community/plausible"
rev = "main"

[[lean_lib]]
name = "Kusudama"

[[lean_lib]]
name = "WristRom"

[[lean_lib]]
name = "JointRom"

[[lean_lib]]
name = "IKFold"

[[lean_lib]]
name = "IKFast"

[[lean_lib]]
name = "IKJerk"
