#!/usr/bin/env python
from misc.utility.scons_hints import *

Import("env")
Import("env_modules")

env_mf = env_modules.Clone()

# Thirdparty: r128.h (header-only, implementation compiled in r128_impl.cpp)

env_mf.Prepend(
    CPPPATH=[
        "#thirdparty/misc/",
        "#thirdparty/webtransportd/",
        "#modules/sqlite/thirdparty",
        "#modules/sqlite",
    ]
)

# Godot source files

module_obj = []
env_mf.add_source_files(module_obj, "*.cpp")

# Thirdparty: webtransportd frame codec (pure C, no dependencies)
env_mf.add_source_files(module_obj, "#thirdparty/webtransportd/frame.c")

env.modules_sources += module_obj
