"""Generates ggml-metal-embed.gen.cpp — embeds the merged Metal shader source
as a C char array, matching the symbol names expected by ggml-metal-device.m
when GGML_METAL_EMBED_LIBRARY is defined.

Mirrors what llama.cpp's CMakeLists.txt does via .incbin assembly, but uses
Godot's plain-C header approach instead so no assembler extension is needed.
"""

import os


def merge_metal_source(metal_file: str, common_h: str, impl_h: str) -> str:
    """Merge ggml-metal.metal with its two inline headers."""
    src = open(metal_file, encoding="utf-8").read()
    common = open(common_h, encoding="utf-8").read()
    impl = open(impl_h, encoding="utf-8").read()
    # cmake uses sed to replace sentinel and include directive
    src = src.replace("__embed_ggml-common.h__", common)
    src = src.replace('#include "ggml-metal-impl.h"', impl)
    return src


def generate_metal_embed(target, source, env):
    """SCons Action: merge Metal sources and write ggml-metal-embed.gen.cpp."""
    metal_file = str(source[0])
    common_h = str(source[1])
    impl_h = str(source[2])
    out_path = str(target[0])

    merged = merge_metal_source(metal_file, common_h, impl_h)

    # Encode as a C string literal (hex-escape all non-ASCII / special chars).
    encoded = ""
    for ch in merged.encode("utf-8"):
        if 32 <= ch < 127 and ch not in (ord('"'), ord("\\"), ord("\0")):
            encoded += chr(ch)
        elif ch == ord("\n"):
            encoded += '\\n"\n"'
        elif ch == ord("\t"):
            encoded += "\\t"
        elif ch == ord("\\"):
            encoded += "\\\\"
        elif ch == ord('"'):
            encoded += '\\"'
        else:
            encoded += f"\\x{ch:02x}"

    os.makedirs(os.path.dirname(out_path), exist_ok=True)

    with open(out_path, "w", encoding="utf-8") as f:
        f.write("/* Auto-generated by modules/llm/metal_builders.py — do not edit. */\n")
        f.write("/* Merged ggml-metal.metal + ggml-common.h + ggml-metal-impl.h    */\n\n")
        f.write("// Symbols referenced by ggml-metal-device.m when\n")
        f.write("// GGML_METAL_EMBED_LIBRARY is defined.\n")
        f.write("extern const char ggml_metallib_start[];\n")
        f.write("extern const char ggml_metallib_end[];\n\n")
        f.write('const char ggml_metallib_start[] =\n"')
        f.write(encoded)
        f.write('";\n\n')
        f.write("const char ggml_metallib_end[] = {0};\n")
