/* humanoid_kusudama_rom_data.h - GENERATED by addb-extract/gen_humanoid_rom_header.py. */
/* Per-bone NORMAL-range swing cones (Kusudama canonical frame, +Y=forward) at the */
/* ANNY REFERENCE phenotype, aggregated over 325 AddBiomechanics With_Arm subjects. */
/* HumanoidKusudamaRom interpolates this over the ANNY phenotype. Do not edit by hand. */
#ifndef HUMANOID_KUSUDAMA_ROM_DATA_H
#define HUMANOID_KUSUDAMA_ROM_DATA_H

namespace HumanoidKusudamaRomData {
struct ConeF { float x, y, z, radius; };
struct BoneRom { const char *bone; const ConeF *cones; int cone_count; float twist; bool clinical; };

static const ConeF TPL_LeftUpperLeg[] = { { -0.679294f, 0.733866f, 0.000000f, 0.882157f }, { 0.679296f, 0.733864f, -0.000000f, 0.898301f } };
static const ConeF TPL_RightUpperLeg[] = { { -0.679297f, 0.733864f, -0.000000f, 0.892698f }, { 0.679296f, 0.733865f, 0.000000f, 0.887758f } };
static const ConeF TPL_LeftLowerLeg[] = { { -0.798356f, 0.602179f, -0.002919f, 0.111151f }, { 0.814645f, 0.579959f, -0.001177f, 0.095776f }, { -0.155852f, 0.987780f, 0.001374f, 0.109306f }, { 0.529756f, 0.848150f, 0.000140f, 0.111393f }, { -0.498440f, 0.866921f, 0.002517f, 0.086396f }, { 0.118388f, 0.992967f, 0.000090f, 0.098250f } };
static const ConeF TPL_RightLowerLeg[] = { { -0.172565f, 0.984998f, 0.000227f, 0.130832f }, { 0.797869f, 0.602823f, -0.003191f, 0.104185f }, { -0.558812f, 0.829294f, -0.000073f, 0.112532f }, { -0.804987f, 0.593291f, -0.001301f, 0.097327f }, { 0.327010f, 0.945018f, 0.002263f, 0.097992f }, { 0.417362f, 0.908738f, 0.002189f, 0.069493f } };
static const ConeF TPL_LeftFoot[] = { { -0.199139f, 0.979907f, 0.011251f, 0.000000f }, { -0.390061f, 0.920789f, -0.000174f, 0.000000f }, { 0.564804f, 0.825016f, -0.018570f, 0.000000f }, { -0.564809f, 0.825012f, -0.018592f, 0.000000f }, { 0.199089f, 0.979917f, 0.011235f, 0.000000f }, { 0.000006f, 0.999887f, 0.015042f, 0.000000f }, { 0.390074f, 0.920783f, -0.000192f, 0.000000f } };
static const ConeF TPL_RightFoot[] = { { -0.199089f, 0.979917f, 0.011235f, 0.000000f }, { 0.390061f, 0.920789f, -0.000174f, 0.000000f }, { 0.199139f, 0.979907f, 0.011251f, 0.000000f }, { -0.564804f, 0.825016f, -0.018570f, 0.000000f }, { -0.000006f, 0.999887f, 0.015042f, 0.000000f }, { 0.564809f, 0.825012f, -0.018592f, 0.000000f }, { -0.390074f, 0.920783f, -0.000192f, 0.000000f } };
static const ConeF TPL_LeftUpperArm[] = { { 0.000000f, 1.000000f, 0.000000f, 2.031324f } };
static const ConeF TPL_RightUpperArm[] = { { 0.000000f, 1.000000f, -0.000000f, 2.031324f } };
static const ConeF TPL_LeftLowerArm[] = { { -0.314013f, 0.948627f, 0.038756f, 0.132929f }, { 0.925648f, 0.375026f, -0.050312f, 0.127812f }, { -0.916023f, 0.397674f, -0.052516f, 0.116568f }, { 0.641037f, 0.767413f, 0.012208f, 0.141106f }, { 0.157292f, 0.986522f, 0.045105f, 0.124748f }, { -0.542239f, 0.840175f, 0.009103f, 0.115548f } };
static const ConeF TPL_RightLowerArm[] = { { -0.664249f, 0.747468f, 0.008019f, 0.123729f }, { 0.659682f, 0.751512f, 0.007042f, 0.119340f }, { -0.213647f, 0.975889f, 0.044676f, 0.149993f }, { 0.909576f, 0.412691f, -0.048550f, 0.116060f }, { 0.221915f, 0.974218f, 0.040651f, 0.122624f }, { -0.917626f, 0.394091f, -0.051528f, 0.127011f } };
static const ConeF TPL_Spine[] = { { 0.000000f, 1.000000f, 0.000000f, 1.570796f } };
static const ConeF TPL_Neck[] = { { 0.0f, 1.0f, 0.0f, 0.785398f } };
static const ConeF TPL_Head[] = { { 0.0f, 1.0f, 0.0f, 0.523599f } };
static const ConeF TPL_Chest[] = { { 0.0f, 1.0f, 0.0f, 0.436332f } };
static const ConeF TPL_UpperChest[] = { { 0.0f, 1.0f, 0.0f, 0.349066f } };
static const ConeF TPL_LeftShoulder[] = { { 0.0f, 1.0f, 0.0f, 0.436332f } };
static const ConeF TPL_RightShoulder[] = { { 0.0f, 1.0f, 0.0f, 0.436332f } };
static const ConeF TPL_LeftHand[] = { { 0.0f, 1.0f, 0.0f, 1.047198f } };
static const ConeF TPL_RightHand[] = { { 0.0f, 1.0f, 0.0f, 1.047198f } };
static const ConeF TPL_LeftToes[] = { { 0.0f, 1.0f, 0.0f, 0.698132f } };
static const ConeF TPL_RightToes[] = { { 0.0f, 1.0f, 0.0f, 0.698132f } };

static const BoneRom TEMPLATE[] = {
	{ "LeftUpperLeg", TPL_LeftUpperLeg, 2, 1.396263f, false },
	{ "RightUpperLeg", TPL_RightUpperLeg, 2, 1.396263f, false },
	{ "LeftLowerLeg", TPL_LeftLowerLeg, 6, 0.000000f, false },
	{ "RightLowerLeg", TPL_RightLowerLeg, 6, 0.000000f, false },
	{ "LeftFoot", TPL_LeftFoot, 7, 0.000000f, false },
	{ "RightFoot", TPL_RightFoot, 7, 0.000000f, false },
	{ "LeftUpperArm", TPL_LeftUpperArm, 1, 3.141593f, false },
	{ "RightUpperArm", TPL_RightUpperArm, 1, 3.141593f, false },
	{ "LeftLowerArm", TPL_LeftLowerArm, 6, 1.570796f, false },
	{ "RightLowerArm", TPL_RightLowerArm, 6, 1.570796f, false },
	{ "Spine", TPL_Spine, 1, 3.141593f, false },
	{ "Neck", TPL_Neck, 1, 2.443461f, true },
	{ "Head", TPL_Head, 1, 1.570796f, true },
	{ "Chest", TPL_Chest, 1, 1.047198f, true },
	{ "UpperChest", TPL_UpperChest, 1, 1.047198f, true },
	{ "LeftShoulder", TPL_LeftShoulder, 1, 0.523599f, true },
	{ "RightShoulder", TPL_RightShoulder, 1, 0.523599f, true },
	{ "LeftHand", TPL_LeftHand, 1, 0.523599f, true },
	{ "RightHand", TPL_RightHand, 1, 0.523599f, true },
	{ "LeftToes", TPL_LeftToes, 1, 0.000000f, true },
	{ "RightToes", TPL_RightToes, 1, 0.000000f, true },
};
static const int TEMPLATE_COUNT = 21;

// ROM is INTERPOLATED over the ANNY phenotype axes (each 0..1, neutral 0.5):
//   scale = clamp(1 + sum ANNY_*_COEF*(axis-0.5), SCALE_MIN, SCALE_MAX).
// Magnitudes are literature-guided (ROM declines with age and weight); the model
// EXTREMES are ~phenotype-invariant in the source data, so the interpolation is smooth
// but gentle. The template above is the ANNY REFERENCE-phenotype ROM (subjects aggregated).
static const float ANNY_AGE_COEF = -0.30f;
static const float ANNY_WEIGHT_COEF = -0.20f;
static const float ANNY_MUSCLE_COEF = -0.10f;
static const float ANNY_GENDER_COEF = -0.06f;
static const float ANNY_HEIGHT_COEF = 0.0f;
static const float ANNY_PROPORTIONS_COEF = 0.0f;
static const float SCALE_MIN = 0.6f;
static const float SCALE_MAX = 1.15f;
static const float MIN_CONE_RADIUS = 0.139626f; // 8 deg floor: never zero-ROM
} // namespace HumanoidKusudamaRomData

#endif // HUMANOID_KUSUDAMA_ROM_DATA_H
